version: '3.7'
services:
  frontend:
    build: 
      context: .
      dockerfile: ./.docker/frontend/Dockerfile
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - 3000:3000

  backend:
    build: 
      context: .
      dockerfile: ./.docker/backend/Dockerfile
    working_dir: /app
    volumes:
      - ./backend:/app
    ports:
      - 3002:3002

  # admin:
  #   build: 
  #     context: .
  #     dockerfile: ./.docker/admin/Dockerfile
  #   working_dir: /app
  #   volumes:
  #     - ./admin:/app
  #   ports:
  #     - 3001:3001

  web:
    build:
      context: .
      dockerfile: ./.docker/nginx/Dockerfile
    volumes:
      - ./.docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
      - frontend
      # - admin
    ports:
      - 80:80
      - 443:443
networks:
  app-tier:
    driver: bridge
