import Head from "next/head";
import CartMain from "../components/Cart/CartMain";
import Footer from "../components/Layout/Footer/Footer";
import Header from "../components/Layout/Header";

export default function Cart() {
  return (
    <>
      <Head>
        <title>Giỏ Hàng</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="icon"
          href="https://nauphache.com/wp-content/uploads/2022/05/nau-pha-che-09-1024x721.png"
        />
      </Head>

      <Header />
      <CartMain />
      <Footer />
    </>
  );
}
