import Head from "next/head";
import CourseMain from "../components/Course/CourseMain";
import Footer from "../components/Layout/Footer/Footer";
import Header from "../components/Layout/Header";

export default function Course() {
  return (
    <>
      <Head>
        <title>Khóa Học - Tiktok Academy</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="icon"
          href="https://nauphache.com/wp-content/uploads/2022/05/nau-pha-che-09-1024x721.png"
        />
      </Head>

      <Header />
      <CourseMain />
      <Footer />
    </>
  );
}
