import Head from "next/head";
import CourseDetailsMain from "../components/CourseDetails/CourseDetailsMain";
import Footer from "../components/Layout/Footer/Footer";
import Header from "../components/Layout/Header";

export default function CourseDetails() {
  return (
    <>
      <Head>
        <title>Chi Tiết Khóa Học</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="icon"
          href="https://nauphache.com/wp-content/uploads/2022/05/nau-pha-che-09-1024x721.png"
        />
      </Head>

      <Header />
      <CourseDetailsMain />
      <Footer />
    </>
  );
}
