import Head from "next/head";
import CourseMain from "../components/Course/CourseMain";
import Footer from "../components/Layout/Footer/Footer";
import Header from "../components/Layout/Header";
import React, { useEffect, useState } from "react";
import Breadcrumb from "../components/Common/Breadcrumb";
import Pagination from "../components/Common/Pagination";

import Link from "next/link";
import axios from "../api/axios";
import * as ReactBootStrap from "react-bootstrap";

import { useRouter } from "next/router";
import ModalCode from "../components/Modals/ModalCode/ModalCode";

export default function MyCourse() {
  const [dataMyCourses, setDataMyCourses] = useState([]);
  const [loading, setLoading] = useState(false);
  const [showModalCode, setShowModalCode] = useState(false);
  const DATA_COURSES_URL = "courses/my-courses";

  const router = useRouter();

  async function getDataCourse() {
    const token = localStorage.getItem("token");
    try {
      await axios
        .get(DATA_COURSES_URL, {
          headers: {
            Authorization: `Bearer ${token}`,
          },
        })
        .then((res) => {
          console.log(res);
          setDataMyCourses(res.data.data);
        });
      setLoading(true);
    } catch (err) {
      console.log(err);
    }
  }

  console.log(dataMyCourses);

  async function getDetailMyCourse(id) {
    router.push("/course-details");
    localStorage.setItem("id", id);
  }

  useEffect(() => {
    getDataCourse();
  }, []);

  function NumToTime(num) {
    var hours = Math.floor(num / 60);
    var minutes = num % 60;
    if (minutes + "".length < 2) {
      minutes = "0" + minutes;
    }
    return hours + ":" + minutes;
  }

  return (
    <>
      <Head>
        <title>Khóa Học Của Tôi</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="icon"
          href="https://nauphache.com/wp-content/uploads/2022/05/nau-pha-che-09-1024x721.png"
        />
      </Head>

      <Header />
      <div>
        <main>
          <Breadcrumb
            breadcrumbTitle="Khóa Học"
            breadcrumbSubTitle="Khóa Học Của Tôi"
          />
          <div className="pb-30"></div>
          <ModalCode
            showModalCode={showModalCode}
            setShowModalCode={setShowModalCode}
          />
          {loading ? (
            <section className="course-content-area pb-90">
              <div className="container">
                <div className="row mb-10">
                  <div className="col-xl-3 col-lg-4 col-md-12">
                    <button
                      type="button"
                      className="btn mb-40 mt-10"
                      onClick={() => setShowModalCode(true)}
                      style={{ backgroundColor: "#597535", color: "white" }}
                    >
                      Nhập CODE Khóa Học Đã Mua !
                    </button>
                    <div className="row mb-10">
                      <div className="col-xl-12 col-lg-4 col-md-12">
                        <div>
                          <div className="course-sidebar-widget mb-20">
                            <div
                              className={`course-sidebar-info ${
                                loading ? "danger" : "content-hidden"
                              }`}
                            >
                              <h3 className="drop-btn">Danh Mục</h3>
                              <ul>
                                <li>
                                  <div className="course-sidebar-list pb-5">
                                    <input
                                      className="edu-check-box"
                                      type="checkbox"
                                      id="e-bus"
                                    />
                                    <label
                                      className="edu-check-label"
                                      htmlFor="e-bus"
                                    >
                                      Tất Cả
                                    </label>
                                  </div>
                                  <div className="course-sidebar-list">
                                    <input
                                      className="edu-check-box"
                                      type="checkbox"
                                      id="e-bus"
                                      value="Cà Phê"
                                    />
                                    <label
                                      className="edu-check-label"
                                      htmlFor="e-bus"
                                    >
                                      Cà Phê
                                    </label>
                                  </div>
                                </li>
                                <li>
                                  <div className="course-sidebar-list">
                                    <input
                                      className="edu-check-box"
                                      type="checkbox"
                                      id="e-dev"
                                      value="Trà Sữa"
                                    />
                                    <label
                                      className="edu-check-label"
                                      htmlFor="e-dev"
                                    >
                                      Trà Sữa
                                    </label>
                                  </div>
                                </li>
                              </ul>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                  <div className="col-xl-9 col-lg-8 col-md-12">
                    <div className="row">
                      {dataMyCourses?.map((item) => (
                        <div
                          className="col-xl-4 col-lg-6 col-md-6"
                          key={item._id}
                        >
                          <div className="protfolio-course-2-wrapper mb-30">
                            <div className="student-course-img">
                              <img src={item.thumbnail} alt="course-img" />
                            </div>
                            <div className="course-cart">
                              <div className="course-info-wrapper">
                                <div className="cart-info-body">
                                  <h3>{item.title}</h3>
                                  <div className="course-action position-absolute bottom-0 mb-20">
                                    <button
                                      className="btn"
                                      onClick={() =>
                                        getDetailMyCourse(item._id)
                                      }
                                      style={{
                                        backgroundColor: "#597535",
                                        color: "white",
                                      }}
                                    >
                                      <i className="flaticon-book pr-10"></i>
                                      Học Ngay!
                                    </button>
                                  </div>
                                </div>
                              </div>
                            </div>
                            <div className="h-100"></div>
                            <div className="course-2-footer">
                              <div className="coursee-clock">
                                <i className="flaticon-clock"></i>
                                <span>Phút/Bài Học</span>
                              </div>
                              <div className="course-creadit">
                                <i className="flaticon-menu-1"></i>
                                <span>{item.numberOfLessons} Bài Học</span>
                              </div>
                            </div>
                          </div>
                        </div>
                      ))}

                      {dataMyCourses === [] && (
                        <div className="d-block justify-content-center">
                          <div className="alert alert-warning" role="alert">
                            Bạn Chưa Có Khóa Học Nào!{" "}
                            <Link href="/course">
                              <a href="#" className="link-info">
                                Đến Trang Khóa Học Ngay!
                              </a>
                            </Link>
                          </div>
                        </div>
                      )}
                    </div>
                  </div>
                </div>
              </div>
            </section>
          ) : (
            <div className="d-flex justify-content-center pb-50">
              <div className="spinner-border" role="status">
                <span className="visually-hidden">Loading...</span>
              </div>
            </div>
          )}
        </main>
      </div>
      <Footer />
    </>
  );
}
